/* Textes fixes de l'interface, en français et en anglais.
   La voix (phrases variées) vit dans voice.ts ; ici, les libellés stables.
   ⚠️ Les labels de genres (deezer.ts) ne se traduisent pas : ce sont les
   clés de l'algo. */

import { isFr } from "./i18n";

const fr = {
  tabs: {
    discover: "Découvrir",
    library: "Bibliothèque",
    search: "Rechercher",
    profile: "Profil",
  },
  discover: {
    filterTitle: "Filtrer le deck",
    filterHint: "Choisis un ou plusieurs genres — vide = tout le catalogue.",
    filterApply: "Appliquer",
    filterClear: "Tout afficher",
    like: "J'AIME",
    nope: "NON",
    later: "À REVOIR",
    reloadFeed: "Ressers-moi ça",
    reswipeAll: "Tout re-swiper",
    offline: "Deezer inaccessible — vérifie ta connexion",
    cancel: "Annuler",
    kvArtist: "Artiste",
    kvAlbum: "Album",
    kvGenres: "Genres",
    kvSource: "Source",
    kvExcerpt: "Extrait",
    seconds: "secondes",
    srcFeatured: "Sélection Tune ✦",
    backFeatured: (a: string) => `${a}, c'est la sélection maison. On assume à 100 %.`,
    backDeezer: (g: string) =>
      `Repéré pour toi dans les charts ${g}. T'as 30 secondes pour trancher.`,
    listenOn: "Écouter en entier sur",
    seeArtist: "Voir l'artiste",
    share: "Partager",
    close: "Fermer",
    obTitle: "C'est quoi, ton son ?",
    obSub: "Coche ce qui te fait vibrer — trois minimum pour bien faire — et ton premier deck sera déjà taillé pour toi.",
    obGo: "Envoie la musique",
    obSkip: "Je préfère me perdre tout seul",
    chartsFallback: "du moment",
    styleFallback: "ce style",
  },
  library: {
    title: "Ma bibliothèque",
    liked: "❤ Aimés",
    later: "⏱ À revoir",
    disliked: "✕ Pas pour moi",
    emptyLiked: "Encore rien par ici.\nSwipe à droite sur ce qui te touche, ça arrive vite.",
    emptyLater: "Rien en attente.\nSwipe vers le haut pour garder un titre au chaud.",
    emptyDisliked: "Personne au placard.\nÇa viendra, fais-toi confiance.",
    removed: (t: string) => `« ${t} » sort de la collec'.`,
    movedToLiked: (t: string) => `« ${t} » passe dans les aimés. Logique.`,
    backToDeck: (t: string) => `« ${t} » retourne dans le deck.`,
  },
  search: {
    title: "Rechercher",
    emptyPrompt: "Tape un nom — on fouille\ntout le catalogue mondial.",
  },
  profile: {
    title: "Profil",
    swipes: "Swipes",
    liked: "Aimés",
    minutes: "Minutes d'écoute",
    favGenres: "Tes genres préférés (algo v1)",
    favArtists: "Tes artistes préférés",
    avoided: "Genres évités",
    emptyGenres: "Swipe quelques titres pour que l'algo apprenne tes goûts.",
    connectSpotify: "Connecter Spotify — mes coups de cœur dans ma playlist",
    spotifyConnected: "Spotify connecté ✓ — déconnecter",
    spotifyDone: "Spotify connecté ! Tes ❤ atterrissent dans ta playlist.",
    spotifyFail: "Connexion Spotify annulée",
    legal: "À propos, confidentialité & mentions légales",
    reset: "Réinitialiser mes données",
    resetTitle: "Réinitialiser",
    resetMsg: "Tes swipes et tes goûts seront effacés.",
    resetConfirmWeb: "Réinitialiser tes swipes et tes goûts ?",
    resetDone: "Données réinitialisées",
  },
  artistView: {
    fallbackName: "Artiste",
    topTracks: "Top titres",
    noPreview: "Aucun extrait disponible.",
    fans: "fans",
    albums: "albums",
  },
};

const en: typeof fr = {
  tabs: {
    discover: "Discover",
    library: "Library",
    search: "Search",
    profile: "Profile",
  },
  discover: {
    filterTitle: "Filter the deck",
    filterHint: "Pick one or more genres — empty means everything.",
    filterApply: "Apply",
    filterClear: "Show everything",
    like: "LIKE",
    nope: "NOPE",
    later: "LATER",
    reloadFeed: "Pour me another",
    reswipeAll: "Re-swipe everything",
    offline: "Deezer unreachable — check your connection",
    cancel: "Cancel",
    kvArtist: "Artist",
    kvAlbum: "Album",
    kvGenres: "Genres",
    kvSource: "Source",
    kvExcerpt: "Preview",
    seconds: "seconds",
    srcFeatured: "Tune selection ✦",
    backFeatured: (a: string) => `${a} is part of our house selection. We fully stand by it.`,
    backDeezer: (g: string) =>
      `Spotted for you in the ${g} charts. You've got 30 seconds to decide.`,
    listenOn: "Listen in full on",
    seeArtist: "See the artist",
    share: "Share",
    close: "Close",
    obTitle: "What's your sound?",
    obSub: "Tick what makes you vibrate — three or more works best — and your first deck will already be cut for you.",
    obGo: "Bring the music",
    obSkip: "I'd rather get lost on my own",
    chartsFallback: "right now",
    styleFallback: "this style",
  },
  library: {
    title: "My library",
    liked: "❤ Liked",
    later: "⏱ Later",
    disliked: "✕ Not for me",
    emptyLiked: "Nothing here yet.\nSwipe right on what moves you — it fills up fast.",
    emptyLater: "Nothing on hold.\nSwipe up to keep a track warm.",
    emptyDisliked: "Nobody in the closet.\nIt'll come, trust yourself.",
    removed: (t: string) => `"${t}" leaves the collection.`,
    movedToLiked: (t: string) => `"${t}" moves to liked. Makes sense.`,
    backToDeck: (t: string) => `"${t}" goes back in the deck.`,
  },
  search: {
    title: "Search",
    emptyPrompt: "Type a name — we'll dig through\nthe entire world catalog.",
  },
  profile: {
    title: "Profile",
    swipes: "Swipes",
    liked: "Liked",
    minutes: "Minutes listened",
    favGenres: "Your favorite genres (algo v1)",
    favArtists: "Your favorite artists",
    avoided: "Avoided genres",
    emptyGenres: "Swipe a few tracks so the algorithm learns your taste.",
    connectSpotify: "Connect Spotify — my likes into my playlist",
    spotifyConnected: "Spotify connected ✓ — disconnect",
    spotifyDone: "Spotify connected! Your ❤ land in your playlist.",
    spotifyFail: "Spotify connection cancelled",
    legal: "About, privacy & legal",
    reset: "Reset my data",
    resetTitle: "Reset",
    resetMsg: "Your swipes and tastes will be erased.",
    resetConfirmWeb: "Reset your swipes and tastes?",
    resetDone: "Data reset",
  },
  artistView: {
    fallbackName: "Artist",
    topTracks: "Top tracks",
    noPreview: "No preview available.",
    fans: "fans",
    albums: "albums",
  },
};

export const S = isFr ? fr : en;
