/* Textes fixes de l'interface, en français et en anglais.
   La voix (phrases variées) vit dans voice.ts ; ici, les libellés stables.
   ⚠️ Les labels de genres (deezer.ts) ne se traduisent pas : ce sont les
   clés de l'algo. */

import { isFr } from "./i18n";

const fr = {
  tabs: {
    discover: "Découvrir",
    library: "Bibliothèque",
    search: "Rechercher",
    profile: "Profil",
  },
  discover: {
    filterTitle: "Filtrer le deck",
    filterHint: "Choisis un ou plusieurs genres — vide = tout le catalogue.",
    filterApply: "Appliquer",
    filterClear: "Tout afficher",
    like: "J'AIME",
    nope: "NON",
    later: "À REVOIR",
    reloadFeed: "Ressers-moi ça",
    reswipeAll: "Tout re-swiper",
    offline: "Deezer inaccessible — vérifie ta connexion",
    cancel: "Annuler",
    kvArtist: "Artiste",
    kvAlbum: "Album",
    kvGenres: "Genres",
    kvSource: "Source",
    kvVisibility: "Visibilité",
    kvExcerpt: "Extrait",
    seconds: "secondes",
    srcFeatured: "Sélection Zicmu ✦",
    backFeatured: (a: string) => `${a}, c'est la sélection maison. On assume à 100 %.`,
    backDeezer: (g: string) =>
      `Repéré pour toi dans les charts ${g}. T'as 30 secondes pour trancher.`,
    listenOn: "Écouter en entier sur",
    seeArtist: "Voir l'artiste",
    share: "Partager",
    close: "Fermer",
    obTitle: "C'est quoi, ton son ?",
    obSub: "Coche ce qui te fait vibrer — trois minimum pour bien faire — et ton premier deck sera déjà taillé pour toi.",
    obGo: "Envoie la musique",
    obSkip: "Je préfère me perdre tout seul",
    chartsFallback: "du moment",
    styleFallback: "ce style",
    sponsored: "Sponsorisé",
    sponsoredLong: "Mise en avant payée par l'artiste",
  },
  library: {
    title: "Ma bibliothèque",
    liked: "❤ Aimés",
    later: "⏱ À revoir",
    disliked: "✕ Pas pour moi",
    emptyLiked: "Encore rien par ici.\nSwipe à droite sur ce qui te touche, ça arrive vite.",
    emptyLater: "Rien en attente.\nSwipe vers le haut pour garder un titre au chaud.",
    emptyDisliked: "Personne au placard.\nÇa viendra, fais-toi confiance.",
    removed: (t: string) => `« ${t} » sort de la collec'.`,
    movedToLiked: (t: string) => `« ${t} » passe dans les aimés. Logique.`,
    backToDeck: (t: string) => `« ${t} » retourne dans le deck.`,
  },
  search: {
    title: "Rechercher",
    emptyPrompt: "Tape un nom — on fouille\ntout le catalogue mondial.",
  },
  profile: {
    title: "Profil",
    swipes: "Swipes",
    liked: "Aimés",
    minutes: "Minutes d'écoute",
    namePlaceholder: "Ton prénom",
    nameTitle: "Comment on t'appelle ?",
    nameSave: "C'est noté",
    openPlaylist: "Voir ma playlist Zicmu sur Spotify",
    favGenres: "Tes genres préférés",
    favArtists: "Tes artistes préférés",
    avoided: "Genres évités",
    emptyGenres: "Swipe quelques titres pour que l'algo apprenne tes goûts.",
    connectSpotify: "Connecter Spotify — mes coups de cœur dans ma playlist",
    spotifyConnected: "Spotify connecté ✓ — déconnecter",
    spotifyDone: "Spotify connecté ! Tes ❤ atterrissent dans ta playlist.",
    spotifyFail: "Connexion Spotify annulée",
    spotifySoon: "La connexion Spotify sera dispo sur la vraie app — Expo Go ne sait pas ramener la clé à la maison.",
    legal: "À propos, confidentialité & mentions légales",
    reset: "Réinitialiser mes données",
    resetTitle: "Réinitialiser",
    resetMsg: "Tes swipes et tes goûts seront effacés.",
    resetConfirmWeb: "Réinitialiser tes swipes et tes goûts ?",
    resetDone: "Données réinitialisées",
  },
  artistView: {
    fallbackName: "Artiste",
    topTracks: "Top titres",
    noPreview: "Aucun extrait disponible.",
    fans: "fans",
    albums: "albums",
  },
  legal: {
    title: "À propos & légal",
    aboutTitle: "Zicmu",
    aboutBody:
      "Zicmu est une application gratuite de découverte musicale : swipe des extraits de 30 secondes, aime ce qui te plaît, et l'algorithme apprend tes goûts. Application sans but commercial.",
    musicTitle: "Musique — attribution Deezer",
    musicBody:
      "Les extraits musicaux (30 secondes), pochettes d'albums, noms d'artistes et classements sont fournis par l'API publique de Deezer. Zicmu n'héberge aucun enregistrement du commerce et ne permet ni téléchargement ni écoute intégrale : pour écouter un titre en entier, tu choisis ta plateforme (Spotify, Apple Music, YouTube, Deezer…) directement depuis la fiche du morceau.",
    privacyTitle: "Confidentialité",
    privacyBody:
      "• Zicmu ne collecte aucune donnée personnelle : pas de compte, pas de tracker, pas de publicité.\n• Tes goûts (swipes, scores de genres et d'artistes) et ta bibliothèque sont stockés uniquement sur ton appareil.\n• Les recherches et le chargement des extraits interrogent l'API Deezer ; ces requêtes sont soumises à la politique de confidentialité de Deezer.\n• Si tu connectes Spotify, l'autorisation reste entre ton appareil et Spotify : Zicmu ne voit jamais ton mot de passe.\n• Tu peux tout effacer à tout moment : Profil → « Réinitialiser mes données », ou en désinstallant l'application.",
    contactTitle: "Contact",
    contactBody:
      "Une question, un signalement, une réclamation de droits ? Une adresse de contact dédiée sera ajoutée avant la sortie publique de l'application.",
    footer: "Zicmu v1.0.0 — fait avec ❤ en France",
  },
};

const en: typeof fr = {
  tabs: {
    discover: "Discover",
    library: "Library",
    search: "Search",
    profile: "Profile",
  },
  discover: {
    filterTitle: "Filter the deck",
    filterHint: "Pick one or more genres — empty means everything.",
    filterApply: "Apply",
    filterClear: "Show everything",
    like: "LIKE",
    nope: "NOPE",
    later: "LATER",
    reloadFeed: "Pour me another",
    reswipeAll: "Re-swipe everything",
    offline: "Deezer unreachable — check your connection",
    cancel: "Cancel",
    kvArtist: "Artist",
    kvAlbum: "Album",
    kvGenres: "Genres",
    kvSource: "Source",
    kvVisibility: "Visibility",
    kvExcerpt: "Preview",
    seconds: "seconds",
    srcFeatured: "Zicmu selection ✦",
    backFeatured: (a: string) => `${a} is part of our house selection. We fully stand by it.`,
    backDeezer: (g: string) =>
      `Spotted for you in the ${g} charts. You've got 30 seconds to decide.`,
    listenOn: "Listen in full on",
    seeArtist: "See the artist",
    share: "Share",
    close: "Close",
    obTitle: "What's your sound?",
    obSub: "Tick what makes you vibrate — three or more works best — and your first deck will already be cut for you.",
    obGo: "Bring the music",
    obSkip: "I'd rather get lost on my own",
    chartsFallback: "right now",
    styleFallback: "this style",
    sponsored: "Sponsored",
    sponsoredLong: "Visibility paid for by the artist",
  },
  library: {
    title: "My library",
    liked: "❤ Liked",
    later: "⏱ Later",
    disliked: "✕ Not for me",
    emptyLiked: "Nothing here yet.\nSwipe right on what moves you — it fills up fast.",
    emptyLater: "Nothing on hold.\nSwipe up to keep a track warm.",
    emptyDisliked: "Nobody in the closet.\nIt'll come, trust yourself.",
    removed: (t: string) => `"${t}" leaves the collection.`,
    movedToLiked: (t: string) => `"${t}" moves to liked. Makes sense.`,
    backToDeck: (t: string) => `"${t}" goes back in the deck.`,
  },
  search: {
    title: "Search",
    emptyPrompt: "Type a name — we'll dig through\nthe entire world catalog.",
  },
  profile: {
    title: "Profile",
    swipes: "Swipes",
    liked: "Liked",
    minutes: "Minutes listened",
    namePlaceholder: "Your name",
    nameTitle: "What should we call you?",
    nameSave: "Got it",
    openPlaylist: "Open my Zicmu playlist on Spotify",
    favGenres: "Your favorite genres",
    favArtists: "Your favorite artists",
    avoided: "Avoided genres",
    emptyGenres: "Swipe a few tracks so the algorithm learns your taste.",
    connectSpotify: "Connect Spotify — my likes into my playlist",
    spotifyConnected: "Spotify connected ✓ — disconnect",
    spotifyDone: "Spotify connected! Your ❤ land in your playlist.",
    spotifyFail: "Spotify connection cancelled",
    spotifySoon: "Spotify connection will be live in the real app — Expo Go can't bring the key back home.",
    legal: "About, privacy & legal",
    reset: "Reset my data",
    resetTitle: "Reset",
    resetMsg: "Your swipes and tastes will be erased.",
    resetConfirmWeb: "Reset your swipes and tastes?",
    resetDone: "Data reset",
  },
  artistView: {
    fallbackName: "Artist",
    topTracks: "Top tracks",
    noPreview: "No preview available.",
    fans: "fans",
    albums: "albums",
  },
  legal: {
    title: "About & legal",
    aboutTitle: "Zicmu",
    aboutBody:
      "Zicmu is a free music discovery app: swipe through 30-second previews, like what moves you, and the algorithm learns your taste. Non-commercial application.",
    musicTitle: "Music — Deezer attribution",
    musicBody:
      "The 30-second music previews, album covers, artist names and charts are provided by Deezer's public API. Zicmu does not host any commercial recording and allows neither downloads nor full playback: to hear a full track, you pick your platform (Spotify, Apple Music, YouTube, Deezer…) right from the track's card.",
    privacyTitle: "Privacy",
    privacyBody:
      "• Zicmu collects no personal data: no account, no tracker, no ads.\n• Your taste (swipes, genre and artist scores) and your library are stored on your device only.\n• Searches and preview loading query the Deezer API; those requests fall under Deezer's privacy policy.\n• If you connect Spotify, the authorization happens between your device and Spotify: Zicmu never sees your password.\n• You can erase everything at any time: Profile → \"Reset my data\", or by uninstalling the app.",
    contactTitle: "Contact",
    contactBody:
      "A question, a report, a rights claim? A dedicated contact address will be added before the app's public release.",
    footer: "Zicmu v1.0.0 — made with ❤ in France",
  },
};

export const S = isFr ? fr : en;
